# Generated by Django 4.2 on 2023-05-04 08:18

from django.db import migrations, models
import newapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='author')),
                ('email', models.EmailField(max_length=254, verbose_name='email_address')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True, verbose_name='book name')),
                ('public', models.CharField(max_length=50, verbose_name='publication')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('retail_price', models.DecimalField(decimal_places=2, default=newapp.models.Book.default_price, max_digits=7, verbose_name='sale_price')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, verbose_name='user_name')),
                ('password', models.CharField(max_length=30, verbose_name='pass_word')),
            ],
        ),
    ]
